### ISSUE TITLE
Ler sobre Epic, story, protótipo, Git Flow e Github Flow

### ISSUE THREAD

**Issue by leoalmeidasa** [leoalmeidasa/My_Study_Plan#13]
- [x] Ler sobre epic
- [x] Ler sobre story
- [x] Ler sobre prototipo
- [x] Entender sobre Git Flow
- [x] Entender sobre GitHUb Flow
