### ISSUE TITLE
Planejar e criar meta na carreira para 6 meses, 1 ano e 2 anos

### ISSUE THREAD

**Issue by leoalmeidasa** [leoalmeidasa/My_Study_Plan#2]
- [x] Planejar Meta na carreira para 6 meses
- [x] Planejar Meta na carreira para 1 ano
- [x] Planejar Meta na carreira para 2 anos
